export const THEMES: Record<string, any> = {
  'midnight-indigo': {
    isDark: false,
    sidebarBg: 'bg-[#1b1c28]',
    sidebarHeader: 'bg-[#1b1c28]',
    sidebarText: 'text-slate-300',
    sidebarHover: 'hover:bg-[#2d3042]',
    sidebarActive: 'bg-[#3b3e54] text-white',
    sidebarBorder: 'border-[#101019]',
    listBg: 'bg-[#f9f9fb]',
    listHeader: 'bg-[#f9f9fb]',
    listText: 'text-slate-700',
    listHover: 'hover:bg-[#f8f9fa]',
    listActive: 'bg-[#eef2f9]',
    listBorder: 'border-slate-200',
    editorBg: 'bg-white',
    editorHeader: 'bg-[#1b1c28]',
    editorText: 'text-slate-800',
    editorBorder: 'border-slate-200',
    dropdownBg: 'bg-white',
    dropdownText: 'text-slate-800',
    previewBg: 'bg-white',
    prose: 'prose',
    codeTheme: 'light'
  },
  'cloud-nine': {
    isDark: false,
    sidebarBg: 'bg-[#f4f4f7]',
    sidebarHeader: 'bg-[#f4f4f7]',
    sidebarText: 'text-slate-600',
    sidebarHover: 'hover:bg-[#e4e4e9]',
    sidebarActive: 'bg-white text-slate-900 shadow-sm',
    sidebarBorder: 'border-slate-200',
    listBg: 'bg-white',
    listHeader: 'bg-white',
    listText: 'text-slate-700',
    listHover: 'hover:bg-[#f8f9fa]',
    listActive: 'bg-[#eef2f9]',
    listBorder: 'border-slate-200',
    editorBg: 'bg-white',
    editorHeader: 'bg-[#f4f4f7]',
    editorText: 'text-slate-800',
    editorBorder: 'border-slate-200',
    dropdownBg: 'bg-white',
    dropdownText: 'text-slate-800',
    previewBg: 'bg-[#fafbfc]',
    prose: 'prose',
    codeTheme: 'light'
  },
  'arctic-night': {
    isDark: true,
    sidebarBg: 'bg-[#eceff4]',
    sidebarHeader: 'bg-[#eceff4]',
    sidebarText: 'text-[#4c566a]',
    sidebarHover: 'hover:bg-[#e5e9f0]',
    sidebarActive: 'bg-[#d8dee9] text-[#2e3440]',
    sidebarBorder: 'border-[#d8dee9]',
    listBg: 'bg-[#434c5e]',
    listHeader: 'bg-[#434c5e]',
    listText: 'text-[#eceff4]',
    listHover: 'hover:bg-[#4c566a]',
    listActive: 'bg-[#3b4252]',
    listBorder: 'border-[#3b4252]',
    editorBg: 'bg-[#2e3440]',
    editorHeader: 'bg-[#eceff4]',
    editorText: 'text-[#eceff4]',
    editorBorder: 'border-[#3b4252]',
    dropdownBg: 'bg-[#3b4252]',
    dropdownText: 'text-[#eceff4]',
    previewBg: 'bg-[#2e3440]',
    prose: 'prose prose-invert prose-p:text-[#e5e9f0] prose-h1:text-white',
    codeTheme: 'dark'
  },
  'cyber-ronin': {
    isDark: true,
    sidebarBg: 'bg-[#1e2329]',
    sidebarHeader: 'bg-[#171b1f]',
    sidebarText: 'text-[#8892b0]',
    sidebarHover: 'hover:bg-[#252b33]',
    sidebarActive: 'bg-[#2b303b] text-[#58a6ff]',
    sidebarBorder: 'border-[#171b1f]',
    listBg: 'bg-[#252b33]',
    listHeader: 'bg-[#1e2329]',
    listText: 'text-[#c9d1d9]',
    listHover: 'hover:bg-[#2b303b]',
    listActive: 'bg-[#343a45]',
    listBorder: 'border-[#1e2329]',
    editorBg: 'bg-[#15191e]',
    editorHeader: 'bg-[#1e2329]',
    editorText: 'text-[#c9d1d9]',
    editorBorder: 'border-[#252b33]',
    dropdownBg: 'bg-[#1e2329]',
    dropdownText: 'text-[#c9d1d9]',
    previewBg: 'bg-[#1a1e24]',
    prose: 'prose prose-invert prose-p:text-[#8b9eb5] prose-h1:text-[#64ffda] prose-a:text-[#58a6ff]',
    codeTheme: 'dark'
  },
  'one-dark-pro': {
    isDark: true,
    sidebarBg: 'bg-[#21252b]',
    sidebarHeader: 'bg-[#21252b]',
    sidebarText: 'text-[#abb2bf]',
    sidebarHover: 'hover:bg-[#2c313a]',
    sidebarActive: 'bg-[#3a3f4b] text-[#61afef]',
    sidebarBorder: 'border-[#181a1f]',
    listBg: 'bg-[#282c34]',
    listHeader: 'bg-[#21252b]',
    listText: 'text-[#abb2bf]',
    listHover: 'hover:bg-[#2c313a]',
    listActive: 'bg-[#3e4451]',
    listBorder: 'border-[#21252b]',
    editorBg: 'bg-[#282c34]',
    editorHeader: 'bg-[#21252b]',
    editorText: 'text-[#abb2bf]',
    editorBorder: 'border-[#3b4048]',
    dropdownBg: 'bg-[#21252b]',
    dropdownText: 'text-[#abb2bf]',
    previewBg: 'bg-[#282c34]',
    prose: 'prose prose-invert prose-p:text-[#abb2bf] prose-h1:text-[#e5c07b] prose-a:text-[#61afef]',
    codeTheme: 'dark'
  },
  'dracula': {
    isDark: true,
    sidebarBg: 'bg-[#21222c]',
    sidebarHeader: 'bg-[#191a21]',
    sidebarText: 'text-[#f8f8f2]',
    sidebarHover: 'hover:bg-[#2b2d3a]',
    sidebarActive: 'bg-[#44475a] text-[#bd93f9]',
    sidebarBorder: 'border-[#191a21]',
    listBg: 'bg-[#282a36]',
    listHeader: 'bg-[#21222c]',
    listText: 'text-[#f8f8f2]',
    listHover: 'hover:bg-[#343746]',
    listActive: 'bg-[#44475a]',
    listBorder: 'border-[#21222c]',
    editorBg: 'bg-[#282a36]',
    editorHeader: 'bg-[#21222c]',
    editorText: 'text-[#f8f8f2]',
    editorBorder: 'border-[#44475a]',
    dropdownBg: 'bg-[#21222c]',
    dropdownText: 'text-[#f8f8f2]',
    previewBg: 'bg-[#282a36]',
    prose: 'prose prose-invert prose-p:text-[#f8f8f2] prose-h1:text-[#bd93f9] prose-a:text-[#8be9fd]',
    codeTheme: 'dark'
  },
  'tokyo-night': {
    isDark: true,
    sidebarBg: 'bg-[#1a1b26]',
    sidebarHeader: 'bg-[#16161e]',
    sidebarText: 'text-[#a9b1d6]',
    sidebarHover: 'hover:bg-[#24283b]',
    sidebarActive: 'bg-[#33467c] text-[#7aa2f7]',
    sidebarBorder: 'border-[#101014]',
    listBg: 'bg-[#1a1b26]',
    listHeader: 'bg-[#16161e]',
    listText: 'text-[#a9b1d6]',
    listHover: 'hover:bg-[#24283b]',
    listActive: 'bg-[#292e42]',
    listBorder: 'border-[#16161e]',
    editorBg: 'bg-[#1a1b26]',
    editorHeader: 'bg-[#16161e]',
    editorText: 'text-[#a9b1d6]',
    editorBorder: 'border-[#292e42]',
    dropdownBg: 'bg-[#16161e]',
    dropdownText: 'text-[#a9b1d6]',
    previewBg: 'bg-[#1a1b26]',
    prose: 'prose prose-invert prose-p:text-[#a9b1d6] prose-h1:text-[#c0caf5] prose-a:text-[#7aa2f7]',
    codeTheme: 'dark'
  },
  'github-dark': {
    isDark: true,
    sidebarBg: 'bg-[#0d1117]',
    sidebarHeader: 'bg-[#010409]',
    sidebarText: 'text-[#c9d1d9]',
    sidebarHover: 'hover:bg-[#161b22]',
    sidebarActive: 'bg-[#1f2937] text-[#58a6ff]',
    sidebarBorder: 'border-[#010409]',
    listBg: 'bg-[#0d1117]',
    listHeader: 'bg-[#010409]',
    listText: 'text-[#c9d1d9]',
    listHover: 'hover:bg-[#161b22]',
    listActive: 'bg-[#1f2937]',
    listBorder: 'border-[#010409]',
    editorBg: 'bg-[#0d1117]',
    editorHeader: 'bg-[#010409]',
    editorText: 'text-[#c9d1d9]',
    editorBorder: 'border-[#21262d]',
    dropdownBg: 'bg-[#161b22]',
    dropdownText: 'text-[#c9d1d9]',
    previewBg: 'bg-[#0d1117]',
    prose: 'prose prose-invert prose-p:text-[#c9d1d9] prose-h1:text-white prose-a:text-[#58a6ff]',
    codeTheme: 'dark'
  },
  'night-owl': {
    isDark: true,
    sidebarBg: 'bg-[#011627]',
    sidebarHeader: 'bg-[#011221]',
    sidebarText: 'text-[#d6deeb]',
    sidebarHover: 'hover:bg-[#0b2942]',
    sidebarActive: 'bg-[#1d3b53] text-[#82aaff]',
    sidebarBorder: 'border-[#010e1a]',
    listBg: 'bg-[#011627]',
    listHeader: 'bg-[#011221]',
    listText: 'text-[#d6deeb]',
    listHover: 'hover:bg-[#0b2942]',
    listActive: 'bg-[#1d3b53]',
    listBorder: 'border-[#011221]',
    editorBg: 'bg-[#011627]',
    editorHeader: 'bg-[#011221]',
    editorText: 'text-[#d6deeb]',
    editorBorder: 'border-[#122d42]',
    dropdownBg: 'bg-[#011221]',
    dropdownText: 'text-[#d6deeb]',
    previewBg: 'bg-[#011627]',
    prose: 'prose prose-invert prose-p:text-[#d6deeb] prose-h1:text-[#c792ea] prose-a:text-[#82aaff]',
    codeTheme: 'dark'
  },
  'monokai-pro': {
    isDark: true,
    sidebarBg: 'bg-[#2d2a2e]',
    sidebarHeader: 'bg-[#221f22]',
    sidebarText: 'text-[#fcfcfa]',
    sidebarHover: 'hover:bg-[#3b383e]',
    sidebarActive: 'bg-[#49464e] text-[#ffd866]',
    sidebarBorder: 'border-[#19181a]',
    listBg: 'bg-[#2d2a2e]',
    listHeader: 'bg-[#221f22]',
    listText: 'text-[#fcfcfa]',
    listHover: 'hover:bg-[#3b383e]',
    listActive: 'bg-[#49464e]',
    listBorder: 'border-[#221f22]',
    editorBg: 'bg-[#2d2a2e]',
    editorHeader: 'bg-[#221f22]',
    editorText: 'text-[#fcfcfa]',
    editorBorder: 'border-[#49464e]',
    dropdownBg: 'bg-[#221f22]',
    dropdownText: 'text-[#fcfcfa]',
    previewBg: 'bg-[#2d2a2e]',
    prose: 'prose prose-invert prose-p:text-[#fcfcfa] prose-h1:text-[#ffd866] prose-a:text-[#78dce8]',
    codeTheme: 'dark'
  },
  'ayu-dark': {
    isDark: true,
    sidebarBg: 'bg-[#0b0e14]',
    sidebarHeader: 'bg-[#0b0e14]',
    sidebarText: 'text-[#bfbdb6]',
    sidebarHover: 'hover:bg-[#11151c]',
    sidebarActive: 'bg-[#1a1e28] text-[#e6b450]',
    sidebarBorder: 'border-[#060809]',
    listBg: 'bg-[#0d1017]',
    listHeader: 'bg-[#0b0e14]',
    listText: 'text-[#bfbdb6]',
    listHover: 'hover:bg-[#131721]',
    listActive: 'bg-[#1a1e28]',
    listBorder: 'border-[#0b0e14]',
    editorBg: 'bg-[#0b0e14]',
    editorHeader: 'bg-[#0b0e14]',
    editorText: 'text-[#bfbdb6]',
    editorBorder: 'border-[#131721]',
    dropdownBg: 'bg-[#0b0e14]',
    dropdownText: 'text-[#bfbdb6]',
    previewBg: 'bg-[#0b0e14]',
    prose: 'prose prose-invert prose-p:text-[#bfbdb6] prose-h1:text-[#e6b450] prose-a:text-[#39bae6]',
    codeTheme: 'dark'
  },
  'winter-is-coming': {
    isDark: true,
    sidebarBg: 'bg-[#011627]',
    sidebarHeader: 'bg-[#001122]',
    sidebarText: 'text-[#d6deeb]',
    sidebarHover: 'hover:bg-[#0b2942]',
    sidebarActive: 'bg-[#172a3a] text-[#87e2ff]',
    sidebarBorder: 'border-[#001122]',
    listBg: 'bg-[#011627]',
    listHeader: 'bg-[#001122]',
    listText: 'text-[#d6deeb]',
    listHover: 'hover:bg-[#0e293f]',
    listActive: 'bg-[#172a3a]',
    listBorder: 'border-[#001122]',
    editorBg: 'bg-[#011627]',
    editorHeader: 'bg-[#001122]',
    editorText: 'text-[#d6deeb]',
    editorBorder: 'border-[#122d42]',
    dropdownBg: 'bg-[#001122]',
    dropdownText: 'text-[#d6deeb]',
    previewBg: 'bg-[#011627]',
    prose: 'prose prose-invert prose-p:text-[#d6deeb] prose-h1:text-[#87e2ff] prose-a:text-[#80cbc4]',
    codeTheme: 'dark'
  },
  'shades-of-purple': {
    isDark: true,
    sidebarBg: 'bg-[#2d2b55]',
    sidebarHeader: 'bg-[#1e1d40]',
    sidebarText: 'text-[#e0d8ff]',
    sidebarHover: 'hover:bg-[#3a3875]',
    sidebarActive: 'bg-[#4b49a5] text-[#fad000]',
    sidebarBorder: 'border-[#1e1d40]',
    listBg: 'bg-[#2d2b55]',
    listHeader: 'bg-[#1e1d40]',
    listText: 'text-[#e0d8ff]',
    listHover: 'hover:bg-[#3a3875]',
    listActive: 'bg-[#4b49a5]',
    listBorder: 'border-[#1e1d40]',
    editorBg: 'bg-[#2d2b55]',
    editorHeader: 'bg-[#1e1d40]',
    editorText: 'text-[#e0d8ff]',
    editorBorder: 'border-[#3a3875]',
    dropdownBg: 'bg-[#1e1d40]',
    dropdownText: 'text-[#e0d8ff]',
    previewBg: 'bg-[#2d2b55]',
    prose: 'prose prose-invert prose-p:text-[#e0d8ff] prose-h1:text-[#fad000] prose-a:text-[#ff7edb]',
    codeTheme: 'dark'
  },
  'catppuccin-mocha': {
    isDark: true,
    sidebarBg: 'bg-[#1e1e2e]',
    sidebarHeader: 'bg-[#181825]',
    sidebarText: 'text-[#cdd6f4]',
    sidebarHover: 'hover:bg-[#28283d]',
    sidebarActive: 'bg-[#313244] text-[#cba6f7]',
    sidebarBorder: 'border-[#11111b]',
    listBg: 'bg-[#1e1e2e]',
    listHeader: 'bg-[#181825]',
    listText: 'text-[#cdd6f4]',
    listHover: 'hover:bg-[#28283d]',
    listActive: 'bg-[#313244]',
    listBorder: 'border-[#181825]',
    editorBg: 'bg-[#1e1e2e]',
    editorHeader: 'bg-[#181825]',
    editorText: 'text-[#cdd6f4]',
    editorBorder: 'border-[#313244]',
    dropdownBg: 'bg-[#181825]',
    dropdownText: 'text-[#cdd6f4]',
    previewBg: 'bg-[#1e1e2e]',
    prose: 'prose prose-invert prose-p:text-[#cdd6f4] prose-h1:text-[#cba6f7] prose-a:text-[#89b4fa]',
    codeTheme: 'dark'
  },
  'github-light': {
    isDark: false,
    sidebarBg: 'bg-[#f6f8fa]',
    sidebarHeader: 'bg-[#f0f2f5]',
    sidebarText: 'text-[#24292f]',
    sidebarHover: 'hover:bg-[#e8ebef]',
    sidebarActive: 'bg-white text-[#0969da] shadow-sm',
    sidebarBorder: 'border-[#d0d7de]',
    listBg: 'bg-white',
    listHeader: 'bg-[#f6f8fa]',
    listText: 'text-[#24292f]',
    listHover: 'hover:bg-[#f3f5f7]',
    listActive: 'bg-[#ddf4ff]',
    listBorder: 'border-[#d0d7de]',
    editorBg: 'bg-white',
    editorHeader: 'bg-[#f6f8fa]',
    editorText: 'text-[#24292f]',
    editorBorder: 'border-[#d0d7de]',
    dropdownBg: 'bg-white',
    dropdownText: 'text-[#24292f]',
    previewBg: 'bg-[#ffffff]',
    prose: 'prose prose-p:text-[#24292f] prose-h1:text-[#1f2328] prose-a:text-[#0969da]',
    codeTheme: 'light'
  },
  'one-light': {
    isDark: false,
    sidebarBg: 'bg-[#fafafa]',
    sidebarHeader: 'bg-[#f0f0f0]',
    sidebarText: 'text-[#383a42]',
    sidebarHover: 'hover:bg-[#e5e5e6]',
    sidebarActive: 'bg-[#dbdbdc] text-[#4078f2]',
    sidebarBorder: 'border-[#dbdbdc]',
    listBg: 'bg-[#fafafa]',
    listHeader: 'bg-[#f0f0f0]',
    listText: 'text-[#383a42]',
    listHover: 'hover:bg-[#ededee]',
    listActive: 'bg-[#d5e4f7]',
    listBorder: 'border-[#dbdbdc]',
    editorBg: 'bg-[#fafafa]',
    editorHeader: 'bg-[#f0f0f0]',
    editorText: 'text-[#383a42]',
    editorBorder: 'border-[#e0e0e0]',
    dropdownBg: 'bg-[#fafafa]',
    dropdownText: 'text-[#383a42]',
    previewBg: 'bg-[#fafafa]',
    prose: 'prose prose-p:text-[#383a42] prose-h1:text-[#e45649] prose-a:text-[#4078f2]',
    codeTheme: 'light'
  },
  'solarized-light': {
    isDark: false,
    sidebarBg: 'bg-[#fdf6e3]',
    sidebarHeader: 'bg-[#eee8d5]',
    sidebarText: 'text-[#586e75]',
    sidebarHover: 'hover:bg-[#e6dfca]',
    sidebarActive: 'bg-[#d6cdb5] text-[#268bd2]',
    sidebarBorder: 'border-[#d3cbb7]',
    listBg: 'bg-[#fdf6e3]',
    listHeader: 'bg-[#eee8d5]',
    listText: 'text-[#586e75]',
    listHover: 'hover:bg-[#f0e9d3]',
    listActive: 'bg-[#ddd5be]',
    listBorder: 'border-[#d3cbb7]',
    editorBg: 'bg-[#fdf6e3]',
    editorHeader: 'bg-[#eee8d5]',
    editorText: 'text-[#586e75]',
    editorBorder: 'border-[#d3cbb7]',
    dropdownBg: 'bg-[#fdf6e3]',
    dropdownText: 'text-[#586e75]',
    previewBg: 'bg-[#fdf6e3]',
    prose: 'prose prose-p:text-[#586e75] prose-h1:text-[#073642] prose-a:text-[#268bd2]',
    codeTheme: 'light'
  },
  'quiet-light': {
    isDark: false,
    sidebarBg: 'bg-[#f5f5f5]',
    sidebarHeader: 'bg-[#ebebeb]',
    sidebarText: 'text-[#333333]',
    sidebarHover: 'hover:bg-[#e0e0e0]',
    sidebarActive: 'bg-[#d4d4d4] text-[#7a3e9d]',
    sidebarBorder: 'border-[#d4d4d4]',
    listBg: 'bg-[#f5f5f5]',
    listHeader: 'bg-[#ebebeb]',
    listText: 'text-[#333333]',
    listHover: 'hover:bg-[#eaeaea]',
    listActive: 'bg-[#e0dff5]',
    listBorder: 'border-[#d4d4d4]',
    editorBg: 'bg-[#f5f5f5]',
    editorHeader: 'bg-[#ebebeb]',
    editorText: 'text-[#333333]',
    editorBorder: 'border-[#d4d4d4]',
    dropdownBg: 'bg-[#f5f5f5]',
    dropdownText: 'text-[#333333]',
    previewBg: 'bg-[#f5f5f5]',
    prose: 'prose prose-p:text-[#333333] prose-h1:text-[#7a3e9d] prose-a:text-[#4b69c6]',
    codeTheme: 'light'
  },
  'ayu-light': {
    isDark: false,
    sidebarBg: 'bg-[#fcfcfc]',
    sidebarHeader: 'bg-[#f3f3f3]',
    sidebarText: 'text-[#5c6166]',
    sidebarHover: 'hover:bg-[#e8e8e8]',
    sidebarActive: 'bg-[#d9d9d9] text-[#f29718]',
    sidebarBorder: 'border-[#dcdcdc]',
    listBg: 'bg-[#fcfcfc]',
    listHeader: 'bg-[#f3f3f3]',
    listText: 'text-[#5c6166]',
    listHover: 'hover:bg-[#efefef]',
    listActive: 'bg-[#fff3d6]',
    listBorder: 'border-[#dcdcdc]',
    editorBg: 'bg-[#fcfcfc]',
    editorHeader: 'bg-[#f3f3f3]',
    editorText: 'text-[#5c6166]',
    editorBorder: 'border-[#dcdcdc]',
    dropdownBg: 'bg-[#fcfcfc]',
    dropdownText: 'text-[#5c6166]',
    previewBg: 'bg-[#fcfcfc]',
    prose: 'prose prose-p:text-[#5c6166] prose-h1:text-[#f29718] prose-a:text-[#36a3d9]',
    codeTheme: 'light'
  },
  'catppuccin-latte': {
    isDark: false,
    sidebarBg: 'bg-[#eff1f5]',
    sidebarHeader: 'bg-[#e6e9ef]',
    sidebarText: 'text-[#4c4f69]',
    sidebarHover: 'hover:bg-[#dce0e8]',
    sidebarActive: 'bg-[#ccd0da] text-[#8839ef]',
    sidebarBorder: 'border-[#ccd0da]',
    listBg: 'bg-[#eff1f5]',
    listHeader: 'bg-[#e6e9ef]',
    listText: 'text-[#4c4f69]',
    listHover: 'hover:bg-[#e4e7ed]',
    listActive: 'bg-[#dddaf8]',
    listBorder: 'border-[#ccd0da]',
    editorBg: 'bg-[#eff1f5]',
    editorHeader: 'bg-[#e6e9ef]',
    editorText: 'text-[#4c4f69]',
    editorBorder: 'border-[#ccd0da]',
    dropdownBg: 'bg-[#eff1f5]',
    dropdownText: 'text-[#4c4f69]',
    previewBg: 'bg-[#eff1f5]',
    prose: 'prose prose-p:text-[#4c4f69] prose-h1:text-[#8839ef] prose-a:text-[#1e66f5]',
    codeTheme: 'light'
  },
  'rose-pine-dawn': {
    isDark: false,
    sidebarBg: 'bg-[#faf4ed]',
    sidebarHeader: 'bg-[#f2e9de]',
    sidebarText: 'text-[#575279]',
    sidebarHover: 'hover:bg-[#e8dfd5]',
    sidebarActive: 'bg-[#dfdad9] text-[#907aa9]',
    sidebarBorder: 'border-[#dfdad9]',
    listBg: 'bg-[#faf4ed]',
    listHeader: 'bg-[#f2e9de]',
    listText: 'text-[#575279]',
    listHover: 'hover:bg-[#f0e7dc]',
    listActive: 'bg-[#e9ddd5]',
    listBorder: 'border-[#dfdad9]',
    editorBg: 'bg-[#faf4ed]',
    editorHeader: 'bg-[#f2e9de]',
    editorText: 'text-[#575279]',
    editorBorder: 'border-[#dfdad9]',
    dropdownBg: 'bg-[#faf4ed]',
    dropdownText: 'text-[#575279]',
    previewBg: 'bg-[#faf4ed]',
    prose: 'prose prose-p:text-[#575279] prose-h1:text-[#907aa9] prose-a:text-[#56949f]',
    codeTheme: 'light'
  },
  'material-lighter': {
    isDark: false,
    sidebarBg: 'bg-[#fafafa]',
    sidebarHeader: 'bg-[#f0f0f0]',
    sidebarText: 'text-[#546e7a]',
    sidebarHover: 'hover:bg-[#e7e7e8]',
    sidebarActive: 'bg-[#ccd7da] text-[#6182b8]',
    sidebarBorder: 'border-[#e0e0e0]',
    listBg: 'bg-[#fafafa]',
    listHeader: 'bg-[#f0f0f0]',
    listText: 'text-[#546e7a]',
    listHover: 'hover:bg-[#eeeeee]',
    listActive: 'bg-[#d6ebf5]',
    listBorder: 'border-[#e0e0e0]',
    editorBg: 'bg-[#fafafa]',
    editorHeader: 'bg-[#f0f0f0]',
    editorText: 'text-[#546e7a]',
    editorBorder: 'border-[#e0e0e0]',
    dropdownBg: 'bg-[#fafafa]',
    dropdownText: 'text-[#546e7a]',
    previewBg: 'bg-[#fafafa]',
    prose: 'prose prose-p:text-[#546e7a] prose-h1:text-[#6182b8] prose-a:text-[#39adb5]',
    codeTheme: 'light'
  },
  'nord-light': {
    isDark: false,
    sidebarBg: 'bg-[#eceff4]',
    sidebarHeader: 'bg-[#e5e9f0]',
    sidebarText: 'text-[#2e3440]',
    sidebarHover: 'hover:bg-[#d8dee9]',
    sidebarActive: 'bg-[#c9d1de] text-[#5e81ac]',
    sidebarBorder: 'border-[#d8dee9]',
    listBg: 'bg-[#eceff4]',
    listHeader: 'bg-[#e5e9f0]',
    listText: 'text-[#2e3440]',
    listHover: 'hover:bg-[#e0e5ed]',
    listActive: 'bg-[#d0d8e5]',
    listBorder: 'border-[#d8dee9]',
    editorBg: 'bg-[#eceff4]',
    editorHeader: 'bg-[#e5e9f0]',
    editorText: 'text-[#2e3440]',
    editorBorder: 'border-[#d8dee9]',
    dropdownBg: 'bg-[#eceff4]',
    dropdownText: 'text-[#2e3440]',
    previewBg: 'bg-[#eceff4]',
    prose: 'prose prose-p:text-[#2e3440] prose-h1:text-[#5e81ac] prose-a:text-[#5e81ac]',
    codeTheme: 'light'
  },
  'everforest-light': {
    isDark: false,
    sidebarBg: 'bg-[#fdf6e3]',
    sidebarHeader: 'bg-[#f4f0d9]',
    sidebarText: 'text-[#5c6a72]',
    sidebarHover: 'hover:bg-[#e9e5ce]',
    sidebarActive: 'bg-[#d5d0b8] text-[#8da101]',
    sidebarBorder: 'border-[#d5d0b8]',
    listBg: 'bg-[#fdf6e3]',
    listHeader: 'bg-[#f4f0d9]',
    listText: 'text-[#5c6a72]',
    listHover: 'hover:bg-[#efebd4]',
    listActive: 'bg-[#e0dcc7]',
    listBorder: 'border-[#d5d0b8]',
    editorBg: 'bg-[#fdf6e3]',
    editorHeader: 'bg-[#f4f0d9]',
    editorText: 'text-[#5c6a72]',
    editorBorder: 'border-[#d5d0b8]',
    dropdownBg: 'bg-[#fdf6e3]',
    dropdownText: 'text-[#5c6a72]',
    previewBg: 'bg-[#fdf6e3]',
    prose: 'prose prose-p:text-[#5c6a72] prose-h1:text-[#8da101] prose-a:text-[#35a77c]',
    codeTheme: 'light'
  },
  'custom': {
    isDark: true,
    sidebarBg: 'bg-[var(--custom-sidebar-bg)]',
    sidebarHeader: 'bg-[var(--custom-sidebar-header)]',
    sidebarText: 'text-[var(--custom-sidebar-text)]',
    sidebarHover: 'hover:bg-white/5',
    sidebarActive: 'bg-white/10 text-white shadow-lg',
    sidebarBorder: 'border-white/10',
    listBg: 'bg-[var(--custom-list-bg)]',
    listHeader: 'bg-[var(--custom-list-header)]',
    listText: 'text-[var(--custom-list-text)]',
    listHover: 'hover:bg-black/10',
    listActive: 'bg-white/10',
    listBorder: 'border-white/10',
    editorBg: 'bg-[var(--custom-editor-bg)]',
    editorHeader: 'bg-[var(--custom-editor-header)]',
    editorText: 'text-[var(--custom-editor-text)]',
    editorBorder: 'border-white/10',
    dropdownBg: 'bg-slate-800',
    dropdownText: 'text-white',
    previewBg: 'bg-[var(--custom-preview-bg)]',
    prose: 'prose prose-invert',
    codeTheme: 'dark'
  },
};
